tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "go-delve/delve"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/cask"
tap "bramstein/webfonttools"
brew "ack"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "openssl"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "x264"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "git-lfs"
brew "gnu-sed", args: ["with-default-names"]
brew "gnupg"
brew "gnupg@1.4"
brew "go"
brew "graphviz"
brew "grep"
brew "imagemagick", args: ["with-webp"]
brew "jq"
brew "m-cli"
brew "mas"
brew "memcached"
brew "moreutils"
brew "mosquitto"
brew "node"
brew "openssh"
brew "p7zip"
brew "python"
brew "rename"
brew "speedtest-cli"
brew "sqlparse"
brew "telnet"
brew "tree"
brew "vim"
brew "wget"
brew "wifi-password"
brew "xsv"
brew "yarn"
brew "zopfli"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/woff2"
brew "go-delve/delve/delve"
cask "1password"
cask "adobe-creative-cloud"
cask "dremio"
cask "firefox"
cask "flux"
cask "hyper"
cask "iterm2"
cask "java"
cask "keybase"
cask "keycastr"
cask "mirador"
cask "ngrok"
cask "sketch"
cask "sketch-toolbox"
cask "slack"
cask "spectacle"
cask "telegram"
cask "visual-studio-code"
cask "zoomus"
cask "caskroom/drivers/garmin-express"
cask "caskroom/drivers/sonos"
cask "caskroom/fonts/font-hack"
cask "caskroom/fonts/font-iosevka"
cask "caskroom/fonts/font-source-code-pro"
mas "CopyClip 2", id: 1020812363
mas "GIPHY CAPTURE", id: 668208984
mas "Harvest", id: 506189836
mas "Icon Slate", id: 439697913
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Shazam", id: 897118787
mas "Skitch", id: 425955336
mas "Xcode", id: 497799835
