brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "csvkit"
brew "curl"
brew "direnv"
brew "ffmpeg"
brew "go"
brew "grep"
brew "node"
brew "jq"
brew "mas"
brew "tfenv"
brew "vim"
brew "youtube-dl"
cask "docker"
cask "firefox"
cask "handbrake"
cask "imageoptim"
cask "iterm2"
cask "keycastr"
cask "maccy"
cask "mmhmm"
cask "ngrok"
cask "skitch"
cask "sonic-pi"
cask "swimat"
cask "tableplus"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "GIPHY CAPTURE", id: 668208984
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
